# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-24.04
  tools:
    nodejs: "20"

  commands:
    - npm ci
    - npm run build
    - mkdir -p "$READTHEDOCS_OUTPUT/html"
    - cp -r dist/. "$READTHEDOCS_OUTPUT/html/"

formats: []
